# Generated by Django 5.2.7 on 2025-10-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='artworks/')),
                ('description', models.TextField(blank=True)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
            ],
        ),
    ]
