# Generated by Django 5.2.7 on 2025-10-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='x',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='y',
        ),
        migrations.AddField(
            model_name='artwork',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
